# Generated by Django 2.0 on 2018-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ret',
            new_name='SearchResult',
        ),
    ]
