# Generated by Django 2.0 on 2018-01-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_totaling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totaling',
            old_name='amount_fee',
            new_name='amount_fees',
        ),
    ]
